### ISSUE TITLE
possibly incorrect calculation of pvalue for synergy index? 

### ISSUE THREAD

**Issue by blostein** [tunsmart/interactionR#12]
Hi, 
I noticed when running interactionR that the p.values for the synergy index do not match the confidence intervals. The null for the synergy index is 1 (S>1 additive, S<1 subadditive). However in the example dataset OCdata, interactionR returns a highly significant p-value even though SI confidence intervals cross 1: 

```r
interactionR::OCdata

model.glm <- glm(oc ~ alc * smk,
                 family = binomial(link = "logit"),
                 data = OCdata
)
## interactionR
value <- interactionR(model.glm,
                      exposure_names = c("alc", "smk"),
                      ci.type = "delta", ci.level = 0.95,
                      em=F)

value$dframe%>%
  filter(Measures=='SI')
  # Measures Estimates     CI.ll    CI.ul            p
#       SI  1.870482 0.6460433 5.415585 0.0007559022
```

In the interactionR function, it looks like SI and se_SI are calculated on the log scale, and then exponentiated for reporting with confidence intervals, which is fine, but then p.SI is calculated as pnorm(exp(lnSI/se_SI)). While under the null hypothesis, Z=lnSI/se_SI is normally distributed around 0, I don't think Z=exp(lnSI/se_SI) is (I think it is log-normal distribution around 1? but not certain). So I think `r p.SI<-1-pnorm(exp(lnSI/se_SI))` should be replaced with either `r p.SI<-1.pnorm(lnSI/se_SI)` or `r p.SI<-1-plnorm(exp(lnSI/se_SI))`. I could be on the wrong track, but it seems incorrect to report small p-values when the confidence interval crosses 1 for the synergy index.

```r 
alpha = 1-0.95
z = qnorm( 1 - alpha/2 )  # critical value
v_cov <- vcov(model.glm)
v_cov1 <- v_cov[c('alc', 'smk', 'alc:smk'), c('alc', 'smk', 'alc:smk')]
b1 <- coef(model.glm)['alc']
b2 <- coef(model.glm)['smk']
b3 <- coef(model.glm)['alc:smk']
lnSI <- log((exp(b1 + b2 + b3) - 1)) - log((exp(b1) + 
                                              exp(b2) - 2))
SI <- exp(lnSI)
SI_noLN = (exp(b1+b2+b3)-1)/((exp(b1)-1)+(exp(b2)-1))
se_SI <- deltamethod(g = ~log((exp(x1 + x2 + x3) - 1)) - 
                       log((exp(x1) + exp(x2) - 2)), mean = c(b1, b2, b3), 
                     cov = v_cov1)
SIL <- exp(lnSI - z * se_SI)
SIU <- exp(lnSI + z * se_SI)

p.SI <- 1 - pnorm(exp(lnSI/se_SI)) # current code in interactionR 
#consider that exp(any number) can never be less than 0. then defining P(X<=exp()) assuming normal(0, 1) seems problematic 
p.lognormal <- 1 - plnorm(exp(lnSI/se_SI))  # possible replacement? 
p.norm_not_exponentiated <- 1 - pnorm(lnSI/se_SI) # possible replacement? 

```

**Comment by yandelrioe** [comment]
Thank you for this, i was hoping someone else notice this.
